//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.04 at 04:37:39 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.uidai.gov.in/authentication/common/types/1.0")
package in.gov.uidai.authentication.common.types._1;
